### PR TITLE
Working

### PR DESCRIPTION
**Pull request by BSGreaves**
@drdreed 
This one's ready, thx.

### CODE REVIEW

**Review by DevDreed — CHANGES_REQUESTED** [review]
Please make the changes to convertTemp function that we discussed.

**Comment by morecallan** [comment]
@BSGreaves @zoeames said you can't have your JS quiz reviewed until this is merged. also, HAVE FUN HAVING YOUR EMAIL BOMBARDED

**Comment by BSGreaves** [comment]
@drdreed Changes made. Cleaned up the enter key listener (reversed "13" and "e.keyCode"). I also cleaned up the primary function convertTemp by turning it into a single if else statement. Removed all unnecessary returns. Thx.

**Review by DevDreed — APPROVED** [review]
👍

**Pull request merged**
